### PR TITLE
develop.md: Some readability refinements

### PR DESCRIPTION
**Pull request by luzpaz**
revamped (markdown + other corrections)

### CODE REVIEW

**Comment by luzpaz** [comment]
Preview: https://github.com/luzpaz/FreeCAD_Conda/blob/develop/develop.md

**Comment by looooo** [comment]
Thanks, I merge this but develop.md is a bit outdated. Conda-forge changed to seperated build and host environments, so this will not work out of the box. I guess some rewrite is necessary.

**Comment by luzpaz** [comment]
Yes, i think it's important to update this and educate the userbase. I'm part of the userbase :) The issue is I'm concerned about b0rking my system by installing miniconda. I'm still trying to understand how to use it on Manjaro (for example, the common practice on manjaro is to use `pacman` to install python modules instead of pip.)

**Comment by looooo** [comment]
To keep your system clean it's best to not initialize conda by default and only when you want it. If you do it like this you can fully separate the system from conda. See the important note at the install section: https://github.com/FreeCAD/FreeCAD_Conda#install-miniconda ; )

Regarding building and developing freecad with conda-packages:
Actually I stooped doing this for quite a while and currently use ubuntu packages for this task. Virtual-envs are not yet supported by c++ ides (like kdevelop) and therefor it's quite difficult to setup a develop-env for freead with conda.

**Comment by luzpaz** [comment]
> Quick question: I'm running Manjaro Linux and I'm interested in testing something that requires conda for dependency management, how do I install and run conda on my box without it borking pacman ?

> A: Just install miniconda from https://docs.conda.io/en/latest/miniconda.html The created environments are totally distinct from your system package managers.

> Q: Just do it is still not creating more confidence. I understand that I will be asked to add miniconda to the system path. so that the python version of miniconda will be utilized over my system python, correct? How will this not mess things up on my system ?

> A: With recent version of conda, if you use `conda config --set auto_activate_base false` then the default conda base environment won't be activated by default and your PATH will stay unchanged. conda is just a function.

> Q: do i need to deactivate it when I'm done using it ?  
> I'm trying to QA test something...and need a setup that is contained and won't pollute the rest of the system. I need it to be idiot proof so if I forget that I enabled it and then run a system update that the conda environment won't be used and potentially b0rk the system

> A: If you activate the environment, you have to deactivate it after (but it only impacts your current running shell, it's not global). So you can just close your shell as well. After you might not even have to activate the environment to use it. You can for example run a command installed in a conda environment by giving its full path. I do that for tools like flake8 or black. I use an alias pointing to the full path.

> Q: can you show me an example of said alias ?

> A: `alias black='/Users/benjaminbertrand/miniconda3/envs/black/bin/black`

> Another answer: Ideally you'd be able to use: alias black='conda run -n black black' .. but conda run is probably not quite ready for that.
It does work, to some extent though, even on Windows/MSYS2 shell.
The advantage is that any activation and PATH manipulation that needs to take place will take place.
> for this to run correctly type conda must indicate that it is a shell function and not anything else.

**Comment by looooo** [comment]
nice.

> conda config --set auto_activate_base false

Didn't know about this one. Works great. Simple typing `conda activate base` will activate the base environment, but switching to any other environment works the same. I guess this is a better option than my suggestion with initConda.

**Pull request merged**
